### ISSUE TITLE
Incorrect slide effect when using targetAttachment="bottom right"

### ISSUE THREAD

**Issue by nag5000** [sir-dunxalot/ember-tooltips#168]
When I use this config
```hbs
{{#popover-on-component side="bottom" targetAttachment="bottom right" as |popover|}}
```
I have both transitions of margin-top **and** margin-left.

UPD: tooltip position on GIFs may differ from your, because I tested addon with merged https://github.com/sir-dunxalot/ember-tooltips/pull/103 and `relativeSidePosition="left"` property.

Actual:
![actual](https://cloud.githubusercontent.com/assets/4932134/22107550/5d1e9a44-de70-11e6-8563-cf5918ec27b8.gif)

Expected: 
![expected](https://cloud.githubusercontent.com/assets/4932134/22107543/51e455f6-de70-11e6-86d6-bfef0a8fe123.gif)

Component generates classes for both sides from targetAttachment:
```css
.ember-popover.ember-tooltip-or-popover-slide.ember-tooltip-or-popover-target-attached-bottom {
    margin-top: -10px;
}
.ember-popover.ember-tooltip-or-popover-slide.ember-tooltip-or-popover-target-attached-right {
    margin-left: -10px;
}

.ember-popover.ember-tooltip-or-popover-slide {
    transition: opacity 200ms ease-out, margin 200ms ease-out;
}
```
