### ISSUE TITLE
Tooltip not in foreground 

### ISSUE THREAD

**Issue by hannesfrank** [sir-dunxalot/ember-tooltips#174]
The tooltip is partially covered by other elements (in my case a `#power-select`):
![ember-tooltip](https://cloud.githubusercontent.com/assets/4137110/22396589/8d580558-e55d-11e6-8f06-43b179bc4d00.png)

This is fixable by setting a high `z-index`:

```css
.ember-tooltip,
.ember-popover {
  z-index: 100;
  // ...
}
```

This could be added to the app styles or changed in the addon itself. 
What is the preferred solution?
