### ISSUE TITLE
Tooltip width does not cover the whole text

### ISSUE THREAD

**Issue by Ericky14** [sir-dunxalot/ember-tooltips#184]
If the text does not contain spaces, it will continue to overflow to the right and background won't cover it.

<img width="425" alt="screen shot 2017-02-08 at 12 00 51 pm" src="https://cloud.githubusercontent.com/assets/21248862/22747943/70b58ca8-edf6-11e6-92be-9c4f66946e9e.png">

If this isn't really a bug, can anyone tell me a way to fix this problem? Thanks.

**Comment by humanchimp** [comment]
You can just override `max-width` in the CSS:

```css
.ember-tooltip,
.ember-popover {
  max-width: unset;
}
```
