### ISSUE TITLE
Styling black on white

### ISSUE THREAD

**Issue by denchen** [sir-dunxalot/ember-tooltips#187]
I thought this should be simple, but I'm having trouble figuring out how to properly style the tooltip for black on white (basically the reverse of what it is now). Because it's black on white, I need to have some kind of border or drop shadow since the background itself is white. The pain point is the arrow, which is defined by `.ember-tooltip::after`. If I put a border on the arrow, the entire border shows up around the tooltip, as such:

![screenshot 2017-03-08 16 03 41](https://cloud.githubusercontent.com/assets/2073768/23729813/d96cb932-0418-11e7-93d8-757c845e80a7.png)

So I thought I would be clever and add borders around the right & bottom edges via:

    .ember-tooltip::after {
      border-right: 1px solid black;
      border-bottom: 1px solid black;
    }

Which ends up looking like:

![screenshot 2017-03-08 16 05 41](https://cloud.githubusercontent.com/assets/2073768/23729862/24ed16c2-0419-11e7-89db-a6a419d92dd3.png)

Great! Except if I set `side="bottom"`, then it breaks:

![screenshot 2017-03-08 16 06 56](https://cloud.githubusercontent.com/assets/2073768/23729888/460a07a2-0419-11e7-988e-e8c4400953be.png)

I've tried using `box-shadow` instead of `border`, but I run into similar issues. I've even tried to set the stacking order by putting `z-index: -1;` in the `:after` psuedo-element, but this had no effect.

I feel like I'm missing some obvious thing to make this all work. As a last resort, I could just eliminate the arrow via `content:none`, but then I might as well use the `popover-on-element` tag instead. Any suggestions?

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips`. [The migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md) details how to apply styling to the two main elements that create a tooltip.

**Comment by basicBrogrammer** [comment]
@sir-dunxalot are there any recommendations on how to style the arrow to share the same shadowing as the tooltip?

**Comment by LucMorrissette** [comment]
@basicBrogrammer While it's not ideal, I set the color of the arrow to be the same as the tooltips border. Like this:

```
.ember-popover[x-placement^="bottom"] .ember-tooltip-arrow {
    border-bottom-color: #ccc;
}

.ember-popover[x-placement^="top"] .ember-tooltip-arrow {
    border-top-color: #ccc;
}
```
![image](https://user-images.githubusercontent.com/2623713/52860348-32e15c80-30fd-11e9-9e50-2e62437944a2.png)

**Comment by basicBrogrammer** [comment]
@LucMorrissette We did the same thing 👍

**Comment by abel-n** [comment]
Hello! I'm curious if I understood it right―I can't have custom colored, bordered tooltips with this addon, can I?

Didn't find any closely related issue apart from this one. The solution mentioned above (arrow having filled with color of border) is not viable.

**Comment by maxfierke** [comment]
You can, you will just likely need to use the `tooltipClass`, `innerClass`, and/or `arrowClass` options and provide your own styles (or override the defaults with CSS). Please see https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/styles/addon.css for how the base styles are implemented.

**Comment by abel-n** [comment]
Indeed, I managed to achieve the desired effect with adding some pseudo elements.

![image](https://user-images.githubusercontent.com/7081757/101522056-ff815900-3986-11eb-8b5b-600cc5491934.png)


Here is the code (for top tooltip only, scss), in case someone wants to play around with something similar:
```scss
.ember-tooltip[x-placement^="top"] {
  background: white;
  border: 1px solid black;
  text-shadow: none;

  .tooltip-inner {
    background-color: white;
    color: black;
  }

  .tooltip-arrow {
    border-top-color: black;

    &:before, &:after {
      content: '';
      display: block;
      position: absolute;
      width: 0;
      height: 0;
      border: 10px solid transparent;
    }

    &:before {
      left: -11px;
      bottom: -15px;
      border-top-color: black;
    }

    &:after {
      left: -10px;
      bottom: -13px;
      border-width: 9px;
      border-top-color: white;
    }
  }
}
```

Based on [this SO post](https://stackoverflow.com/questions/36872206/css-tooltip-with-arrow-and-border)
